### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by Tmyann** [tonyjo/edlsm_pytorch#2]
Hi，what‘s the tensorflow version of this code?

**Comment by Tmyann** [comment]
Sovled, tf.app.flags is only compatible with version 1.0-1.4.

**Comment by tonyjo** [comment]
> Sovled, tf.app.flags is only compatible with version 1.0-1.4.

Yes. I used it for convenience. There is no reason why it can't be replaced by **argparser** .
